In [1]:
import os 

from dotenv import load_dotenv
load_dotenv()



KAGGLE_USERNAME = os.getenv('KAGGLE_USERNAME')
KAGGLE_KEY = os.getenv('KAGGLE_KEY')

In [2]:
!kaggle datasets download -d ankitbansal06/retail-orders

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
retail-orders.zip: Skipping, found more recently modified local copy (use --force to force download)

In [3]:
#!unzip retail-orders.zip -d orders

In [4]:
import pandas as pd

df = pd.read_csv('orders/orders.csv')

In [5]:
df.head(30)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,Not Available,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,Not Available,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,unknown,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3
20,21,2022-10-05,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Binders,OFF-BI-10002215,20,20,4,2
21,22,2023-07-16,Standard Class,Corporate,United States,Fremont,Nebraska,68025,Central,Office Supplies,Art,OFF-AR-10000246,20,20,7,4
22,23,2023-05-06,Standard Class,Corporate,United States,Fremont,Nebraska,68025,Central,Office Supplies,Appliances,OFF-AP-10001492,50,60,7,3
23,24,2023-05-21,Second Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Furniture,Chairs,FUR-CH-10002774,60,70,2,4
24,25,2023-02-24,Standard Class,Consumer,United States,Orem,Utah,84057,West,Furniture,Tables,FUR-TA-10000577,900,1040,3,5
25,26,2022-06-20,Second Class,Consumer,United States,Los Angeles,California,90049,West,Office Supplies,Binders,OFF-BI-10001634,10,10,2,5
26,27,2022-02-08,Second Class,Consumer,United States,Los Angeles,California,90049,West,Technology,Accessories,TEC-AC-10003027,80,90,3,3
27,28,2023-12-11,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Furniture,Bookcases,FUR-BO-10004834,2740,3080,7,3
28,29,2022-08-21,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Office Supplies,Binders,OFF-BI-10000474,10,10,2,5
29,30,2022-08-14,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Furniture,Furnishings,FUR-FU-10004848,100,120,3,4

In [6]:
df.shape

(9994, 16)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order Id          9994 non-null   int64
 1   Order Date        9994 non-null   object
 2   Ship Mode         9993 non-null   object
 3   Segment           9994 non-null   object
 4   Country           9994 non-null   object
 5   City              9994 non-null   object
 6   State             9994 non-null   object
 7   Postal Code       9994 non-null   int64
 8   Region            9994 non-null   object
 9   Category          9994 non-null   object
 10  Sub Category      9994 non-null   object
 11  Product Id        9994 non-null   object
 12  cost price        9994 non-null   int64
 13  List Price        9994 non-null   int64
 14  Quantity          9994 non-null   int64
 15  Discount Percent  9994 non-null   int64
dtypes: int64(6), object(10)
memory usage: 1.2+ MB

In [8]:
df.isna().sum()

Order Id            0
Order Date          0
Ship Mode           1
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Category            0
Sub Category        0
Product Id          0
cost price          0
List Price          0
Quantity            0
Discount Percent    0
dtype: int64

In [9]:
for col in df.select_dtypes(include = object):
    if col != 'Order Date':
        print(f'Unique values in {col}')
        print(df[col].unique())

Unique values in Ship Mode
['Second Class' 'Standard Class' 'Not Available' 'unknown' 'First Class'
 nan 'Same Day']
Unique values in Segment
['Consumer' 'Corporate' 'Home Office']
Unique values in Country
['United States']
Unique values in City
['Henderson' 'Los Angeles' 'Fort Lauderdale' 'Concord' 'Seattle'
 'Fort Worth' 'Madison' 'West Jordan' 'San Francisco' 'Fremont'
 'Philadelphia' 'Orem' 'Houston' 'Richardson' 'Naperville' 'Melbourne'
 'Eagan' 'Westland' 'Dover' 'New Albany' 'New York City' 'Troy' 'Chicago'
 'Gilbert' 'Springfield' 'Jackson' 'Memphis' 'Decatur' 'Durham' 'Columbia'
 'Rochester' 'Minneapolis' 'Portland' 'Saint Paul' 'Aurora' 'Charlotte'
 'Orland Park' 'Urbandale' 'Columbus' 'Bristol' 'Wilmington' 'Bloomington'
 'Phoenix' 'Roseville' 'Independence' 'Pasadena' 'Newark' 'Franklin'
 'Scottsdale' 'San Jose' 'Edmond' 'Carlsbad' 'San Antonio' 'Monroe'
 'Fairfield' 'Grand Prairie' 'Redlands' 'Hamilton' 'Westfield' 'Akron'
 'Denver' 'Dallas' 'Whittier' 'Saginaw' 'Medina' 'Dublin' 'Detroit'
 'Tampa' 'Santa Clara' 'Lakeville' 'San Diego' 'Brentwood' 'Chapel Hill'
 'Morristown' 'Cincinnati' 'Inglewood' 'Tamarac' 'Colorado Springs'
 'Belleville' 'Taylor' 'Lakewood' 'Arlington' 'Arvada' 'Hackensack'
 'Saint Petersburg' 'Long Beach' 'Hesperia' 'Murfreesboro' 'Layton'
 'Austin' 'Lowell' 'Manchester' 'Harlingen' 'Tucson' 'Quincy'
 'Pembroke Pines' 'Des Moines' 'Peoria' 'Las Vegas' 'Warwick' 'Miami'
 'Huntington Beach' 'Richmond' 'Louisville' 'Lawrence' 'Canton'
 'New Rochelle' 'Gastonia' 'Jacksonville' 'Auburn' 'Norman' 'Park Ridge'
 'Amarillo' 'Lindenhurst' 'Huntsville' 'Fayetteville' 'Costa Mesa'
 'Parker' 'Atlanta' 'Gladstone' 'Great Falls' 'Lakeland' 'Montgomery'
 'Mesa' 'Green Bay' 'Anaheim' 'Marysville' 'Salem' 'Laredo' 'Grove City'
 'Dearborn' 'Warner Robins' 'Vallejo' 'Mission Viejo' 'Rochester Hills'
 'Plainfield' 'Sierra Vista' 'Vancouver' 'Cleveland' 'Tyler' 'Burlington'
 'Waynesboro' 'Chester' 'Cary' 'Palm Coast' 'Mount Vernon' 'Hialeah'
 'Oceanside' 'Evanston' 'Trenton' 'Cottage Grove' 'Bossier City'
 'Lancaster' 'Asheville' 'Lake Elsinore' 'Omaha' 'Edmonds' 'Santa Ana'
 'Milwaukee' 'Florence' 'Lorain' 'Linden' 'Salinas' 'New Brunswick'
 'Garland' 'Norwich' 'Alexandria' 'Toledo' 'Farmington' 'Riverside'
 'Torrance' 'Round Rock' 'Boca Raton' 'Virginia Beach' 'Murrieta'
 'Olympia' 'Washington' 'Jefferson City' 'Saint Peters' 'Rockford'
 'Brownsville' 'Yonkers' 'Oakland' 'Clinton' 'Encinitas' 'Roswell'
 'Jonesboro' 'Antioch' 'Homestead' 'La Porte' 'Lansing' 'Cuyahoga Falls'
 'Reno' 'Harrisonburg' 'Escondido' 'Royal Oak' 'Rockville' 'Coral Springs'
 'Buffalo' 'Boynton Beach' 'Gulfport' 'Fresno' 'Greenville' 'Macon'
 'Cedar Rapids' 'Providence' 'Pueblo' 'Deltona' 'Murray' 'Middletown'
 'Freeport' 'Pico Rivera' 'Provo' 'Pleasant Grove' 'Smyrna' 'Parma'
 'Mobile' 'New Bedford' 'Irving' 'Vineland' 'Glendale' 'Niagara Falls'
 'Thomasville' 'Westminster' 'Coppell' 'Pomona' 'North Las Vegas'
 'Allentown' 'Tempe' 'Laguna Niguel' 'Bridgeton' 'Everett' 'Watertown'
 'Appleton' 'Bellevue' 'Allen' 'El Paso' 'Grapevine' 'Carrollton' 'Kent'
 'Lafayette' 'Tigard' 'Skokie' 'Plano' 'Suffolk' 'Indianapolis' 'Bayonne'
 'Greensboro' 'Baltimore' 'Kenosha' 'Olathe' 'Tulsa' 'Redmond' 'Raleigh'
 'Muskogee' 'Meriden' 'Bowling Green' 'South Bend' 'Spokane' 'Keller'
 'Port Orange' 'Medford' 'Charlottesville' 'Missoula' 'Apopka' 'Reading'
 'Broomfield' 'Paterson' 'Oklahoma City' 'Chesapeake' 'Lubbock'
 'Johnson City' 'San Bernardino' 'Leominster' 'Bozeman' 'Perth Amboy'
 'Ontario' 'Rancho Cucamonga' 'Moorhead' 'Mesquite' 'Stockton'
 'Ormond Beach' 'Sunnyvale' 'York' 'College Station' 'Saint Louis'
 'Manteca' 'San Angelo' 'Salt Lake City' 'Knoxville' 'Little Rock'
 'Lincoln Park' 'Marion' 'Littleton' 'Bangor' 'Southaven' 'New Castle'
 'Midland' 'Sioux Falls' 'Fort Collins' 'Clarksville' 'Sacramento'
 'Thousand Oaks' 'Malden' 'Holyoke' 'Albuquerque' 'Sparks' 'Coachella'
 'Elmhurst' 'Passaic' 'North Charleston' 'Newport News' 'Jamestown'
 'Mishawaka' 'La Quinta' 'Tallahassee' 'Nashville' 'Bellingham'
 'Woodstock' 'Haltom City' 'Wheeling' 'Summerville' 'Hot Springs'
 'Englewood' 'Las Cruces' 'Hoover' 'Frisco' 'Vacaville' 'Waukesha'
 'Bakersfield' 'Pompano Beach' 'Corpus Christi' 'Redondo Beach' 'Orlando'
 'Orange' 'Lake Charles' 'Highland Park' 'Hempstead' 'Noblesville'
 'Apple Valley' 'Mount Pleasant' 'Sterling Heights' 'Eau Claire' 'Pharr'
 'Billings' 'Gresham' 'Chattanooga' 'Meridian' 'Bolingbrook' 'Maple Grove'
 'Woodland' 'Missouri City' 'Pearland' 'San Mateo' 'Grand Rapids'
 'Visalia' 'Overland Park' 'Temecula' 'Yucaipa' 'Revere' 'Conroe'
 'Tinley Park' 'Dubuque' 'Dearborn Heights' 'Santa Fe' 'Hickory'
 'Carol Stream' 'Saint Cloud' 'North Miami' 'Plantation'
 'Port Saint Lucie' 'Rock Hill' 'Odessa' 'West Allis' 'Chula Vista'
 'Manhattan' 'Altoona' 'Thornton' 'Champaign' 'Texarkana' 'Edinburg'
 'Baytown' 'Greenwood' 'Woonsocket' 'Superior' 'Bedford' 'Covington'
 'Broken Arrow' 'Miramar' 'Hollywood' 'Deer Park' 'Wichita' 'Mcallen'
 'Iowa City' 'Boise' 'Cranston' 'Port Arthur' 'Citrus Heights'
 'The Colony' 'Daytona Beach' 'Bullhead City' 'Portage' 'Fargo' 'Elkhart'
 'San Gabriel' 'Margate' 'Sandy Springs' 'Mentor' 'Lawton' 'Hampton'
 'Rome' 'La Crosse' 'Lewiston' 'Hattiesburg' 'Danville' 'Logan'
 'Waterbury' 'Athens' 'Avondale' 'Marietta' 'Yuma' 'Wausau' 'Pasco'
 'Oak Park' 'Pensacola' 'League City' 'Gaithersburg' 'Lehi' 'Tuscaloosa'
 'Moreno Valley' 'Georgetown' 'Loveland' 'Chandler' 'Helena' 'Kirkwood'
 'Waco' 'Frankfort' 'Bethlehem' 'Grand Island' 'Woodbury' 'Rogers'
 'Clovis' 'Jupiter' 'Santa Barbara' 'Cedar Hill' 'Norfolk' 'Draper'
 'Ann Arbor' 'La Mesa' 'Pocatello' 'Holland' 'Milford' 'Buffalo Grove'
 'Lake Forest' 'Redding' 'Chico' 'Utica' 'Conway' 'Cheyenne' 'Owensboro'
 'Caldwell' 'Kenner' 'Nashua' 'Bartlett' 'Redwood City' 'Lebanon'
 'Santa Maria' 'Des Plaines' 'Longview' 'Hendersonville' 'Waterloo'
 'Cambridge' 'Palatine' 'Beverly' 'Eugene' 'Oxnard' 'Renton' 'Glenview'
 'Delray Beach' 'Commerce City' 'Texas City' 'Wilson' 'Rio Rancho'
 'Goldsboro' 'Montebello' 'El Cajon' 'Beaumont' 'West Palm Beach'
 'Abilene' 'Normal' 'Saint Charles' 'Camarillo' 'Hillsboro' 'Burbank'
 'Modesto' 'Garden City' 'Atlantic City' 'Longmont' 'Davis' 'Morgan Hill'
 'Clifton' 'Sheboygan' 'East Point' 'Rapid City' 'Andover' 'Kissimmee'
 'Shelton' 'Danbury' 'Sanford' 'San Marcos' 'Greeley' 'Mansfield' 'Elyria'
 'Twin Falls' 'Coral Gables' 'Romeoville' 'Marlborough' 'Laurel' 'Bryan'
 'Pine Bluff' 'Aberdeen' 'Hagerstown' 'East Orange' 'Arlington Heights'
 'Oswego' 'Coon Rapids' 'San Clemente' 'San Luis Obispo' 'Springdale'
 'Lodi' 'Mason']
Unique values in State
['Kentucky' 'California' 'Florida' 'North Carolina' 'Washington' 'Texas'
 'Wisconsin' 'Utah' 'Nebraska' 'Pennsylvania' 'Illinois' 'Minnesota'
 'Michigan' 'Delaware' 'Indiana' 'New York' 'Arizona' 'Virginia'
 'Tennessee' 'Alabama' 'South Carolina' 'Oregon' 'Colorado' 'Iowa' 'Ohio'
 'Missouri' 'Oklahoma' 'New Mexico' 'Louisiana' 'Connecticut' 'New Jersey'
 'Massachusetts' 'Georgia' 'Nevada' 'Rhode Island' 'Mississippi'
 'Arkansas' 'Montana' 'New Hampshire' 'Maryland' 'District of Columbia'
 'Kansas' 'Vermont' 'Maine' 'South Dakota' 'Idaho' 'North Dakota'
 'Wyoming' 'West Virginia']
Unique values in Region
['South' 'West' 'Central' 'East']
Unique values in Category
['Furniture' 'Office Supplies' 'Technology']
Unique values in Sub Category
['Bookcases' 'Chairs' 'Labels' 'Tables' 'Storage' 'Furnishings' 'Art'
 'Phones' 'Binders' 'Appliances' 'Paper' 'Accessories' 'Envelopes'
 'Fasteners' 'Supplies' 'Machines' 'Copiers']
Unique values in Product Id
['FUR-BO-10001798' 'FUR-CH-10000454' 'OFF-LA-10000240' ...
 'OFF-AP-10003099' 'TEC-PH-10002645' 'OFF-ST-10001627']

In [10]:
# Replace Invalids: In pandas, replace the entries 'Not Available' and 'unknown' in the Ship Mode column with NaN.
import numpy as np
df['Ship Mode']= df['Ship Mode'].replace(['Not Available','unknown'], np.nan)


print(df['Ship Mode'].unique())

['Second Class' 'Standard Class' nan 'First Class' 'Same Day']

In [11]:
# 4.3. Rename Columns: Show how to rename all DataFrame columns by lowercasing and replacing spaces with underscores.

df.columns = df.columns.str.lower().str.replace(' ','_')

print(df.columns)

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

In [12]:
df['discout'] = df['list_price'] * df['discount_percent']/100

df[['list_price','discount_percent','discout']].head()

   list_price  discount_percent  discout
0         260                 2      5.2
1         730                 3     21.9
2          10                 5      0.5
3         960                 2     19.2
4          20                 5      1.0

In [13]:
df['selling_price'] = df['list_price'] - df['discout']
df[['list_price','discout','selling_price']].head()

   list_price  discout  selling_price
0         260      5.2          254.8
1         730     21.9          708.1
2          10      0.5            9.5
3         960     19.2          940.8
4          20      1.0           19.0

In [14]:
df['profit']=df['selling_price']-df['cost_price']
df[['selling_price','cost_price','profit']].head()

   selling_price  cost_price  profit
0          254.8         240    14.8
1          708.1         600   108.1
2            9.5          10    -0.5
3          940.8         780   160.8
4           19.0          20    -1.0

In [15]:

df.drop(['cost_price','list_price','discount_percent'],axis = 1,inplace=True)

In [16]:
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discout,selling_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0

In [17]:


df['order_date'] = pd.to_datetime(df['order_date'],format = 'ISO8601')
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discout,selling_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

### Database Operations

In [18]:
# Connection String: Using environment variables HOST, DATABASE, USER, PASSWORD,and PORT, construct the SQLAlchemy connection string for a MySQL database

!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in ./vvv/lib/python3.12/site-packages (2.0.41)
Requirement already satisfied: greenlet>=1 in ./vvv/lib/python3.12/site-packages (from sqlalchemy) (3.2.2)
Requirement already satisfied: typing-extensions>=4.6.0 in ./vvv/lib/python3.12/site-packages (from sqlalchemy) (4.13.2)

In [19]:
!pip install pymysql

Requirement already satisfied: pymysql in ./vvv/lib/python3.12/site-packages (1.1.1)

In [20]:
import os

from dotenv import load_dotenv

load_dotenv()

DATABASE = os.getenv('DATABASE')
USER = os.getenv('USER')
PASSWORD = os.getenv('PASSWORD')
HOST = os.getenv('HOST')
PORT = os.getenv('PORT')

In [21]:
# connection string
from sqlalchemy import create_engine

engine = create_engine(f'mysql+pymysql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}',echo = True)

In [22]:
!pip install cryptography

Requirement already satisfied: cryptography in ./vvv/lib/python3.12/site-packages (45.0.3)
Requirement already satisfied: cffi>=1.14 in ./vvv/lib/python3.12/site-packages (from cryptography) (1.17.1)
Requirement already satisfied: pycparser in ./vvv/lib/python3.12/site-packages (from cffi>=1.14->cryptography) (2.22)

In [23]:
try:
    with engine.connect() as connection:
        print('Connection is sucessful!')
except Exception as e:
    print('Connection failed',e)

2025-06-08 18:18:42,542 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2025-06-08 18:18:42,551 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-06-08 18:18:42,569 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2025-06-08 18:18:42,578 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-06-08 18:18:42,583 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2025-06-08 18:18:42,591 INFO sqlalchemy.engine.Engine [raw sql] {}
Connection is sucessful!

In [24]:
# Write to SQL: Write the DataFrame into a table named orders in the connected database, appending if the table exists and omitting the index.
df.to_sql('orders',con=engine,if_exists='replace',index=False)

2025-06-08 18:18:42,855 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-06-08 18:18:42,892 INFO sqlalchemy.engine.Engine DESCRIBE `retail`.`orders`
2025-06-08 18:18:42,894 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-06-08 18:18:42,915 INFO sqlalchemy.engine.Engine DESCRIBE `retail`.`orders`
2025-06-08 18:18:42,919 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-06-08 18:18:42,935 INFO sqlalchemy.engine.Engine SHOW FULL TABLES FROM `retail`
2025-06-08 18:18:42,938 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-06-08 18:18:42,947 INFO sqlalchemy.engine.Engine SHOW FULL TABLES FROM `retail`
2025-06-08 18:18:42,952 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-06-08 18:18:43,008 INFO sqlalchemy.engine.Engine SHOW CREATE TABLE `orders`
2025-06-08 18:18:43,015 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-06-08 18:18:43,030 INFO sqlalchemy.engine.Engine
DROP TABLE orders
2025-06-08 18:18:43,032 INFO sqlalchemy.engine.Engine [no key 0.00184s] {}
2025-06-08 18:18:43,116 INFO sqlalchemy.engine.Engine
CREATE TABLE orders (
	order_id BIGINT,
	order_date DATETIME,
	ship_mode TEXT,
	segment TEXT,
	country TEXT,
	city TEXT,
	state TEXT,
	postal_code BIGINT,
	region TEXT,
	category TEXT,
	sub_category TEXT,
	product_id TEXT,
	quantity BIGINT,
	discout FLOAT(53),
	selling_price FLOAT(53),
	profit FLOAT(53)
)


2025-06-08 18:18:43,122 INFO sqlalchemy.engine.Engine [no key 0.00602s] {}
2025-06-08 18:18:43,913 INFO sqlalchemy.engine.Engine INSERT INTO orders (order_id, order_date, ship_mode, segment, country, city, state, postal_code, region, category, sub_category, product_id, quantity, discout, selling_price, profit) VALUES (%(order_id)s, %(order_date)s, %(ship_mode)s, %(segment)s, %(country)s, %(city)s, %(state)s, %(postal_code)s, %(region)s, %(category)s, %(sub_category)s, %(product_id)s, %(quantity)s, %(discout)s, %(selling_price)s, %(profit)s)
2025-06-08 18:18:43,919 INFO sqlalchemy.engine.Engine [generated in 0.52210s] [{'order_id': 1, 'order_date': datetime.datetime(2023, 3, 1, 0, 0), 'ship_mode': 'Second Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Henderson', 'state': 'Kentucky', 'postal_code': 42420, 'region': 'South', 'category': 'Furniture', 'sub_category': 'Bookcases', 'product_id': 'FUR-BO-10001798', 'quantity': 2, 'discout': 5.2, 'selling_price': 254.8, 'profit': 14.800000000000011}, {'order_id': 2, 'order_date': datetime.datetime(2023, 8, 15, 0, 0), 'ship_mode': 'Second Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Henderson', 'state': 'Kentucky', 'postal_code': 42420, 'region': 'South', 'category': 'Furniture', 'sub_category': 'Chairs', 'product_id': 'FUR-CH-10000454', 'quantity': 3, 'discout': 21.9, 'selling_price': 708.1, 'profit': 108.10000000000002}, {'order_id': 3, 'order_date': datetime.datetime(2023, 1, 10, 0, 0), 'ship_mode': 'Second Class', 'segment': 'Corporate', 'country': 'United States', 'city': 'Los Angeles', 'state': 'California', 'postal_code': 90036, 'region': 'West', 'category': 'Office Supplies', 'sub_category': 'Labels', 'product_id': 'OFF-LA-10000240', 'quantity': 2, 'discout': 0.5, 'selling_price': 9.5, 'profit': -0.5}, {'order_id': 4, 'order_date': datetime.datetime(2022, 6, 18, 0, 0), 'ship_mode': 'Standard Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Fort Lauderdale', 'state': 'Florida', 'postal_code': 33311, 'region': 'South', 'category': 'Furniture', 'sub_category': 'Tables', 'product_id': 'FUR-TA-10000577', 'quantity': 5, 'discout': 19.2, 'selling_price': 940.8, 'profit': 160.79999999999995}, {'order_id': 5, 'order_date': datetime.datetime(2022, 7, 13, 0, 0), 'ship_mode': 'Standard Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Fort Lauderdale', 'state': 'Florida', 'postal_code': 33311, 'region': 'South', 'category': 'Office Supplies', 'sub_category': 'Storage', 'product_id': 'OFF-ST-10000760', 'quantity': 2, 'discout': 1.0, 'selling_price': 19.0, 'profit': -1.0}, {'order_id': 6, 'order_date': datetime.datetime(2022, 3, 13, 0, 0), 'ship_mode': None, 'segment': 'Consumer', 'country': 'United States', 'city': 'Los Angeles', 'state': 'California', 'postal_code': 90032, 'region': 'West', 'category': 'Furniture', 'sub_category': 'Furnishings', 'product_id': 'FUR-FU-10001487', 'quantity': 7, 'discout': 1.5, 'selling_price': 48.5, 'profit': -1.5}, {'order_id': 7, 'order_date': datetime.datetime(2022, 12, 28, 0, 0), 'ship_mode': 'Standard Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Los Angeles', 'state': 'California', 'postal_code': 90032, 'region': 'West', 'category': 'Office Supplies', 'sub_category': 'Art', 'product_id': 'OFF-AR-10002833', 'quantity': 4, 'discout': 0.3, 'selling_price': 9.7, 'profit': -0.3000000000000007}, {'order_id': 8, 'order_date': datetime.datetime(2022, 1, 25, 0, 0), 'ship_mode': 'Standard Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Los Angeles', 'state': 'California', 'postal_code': 90032, 'region': 'West', 'category': 'Technology', 'sub_category': 'Phones', 'product_id': 'TEC-PH-10002275', 'quantity': 6, 'discout': 45.5, 'selling_price': 864.5, 'profit': 4.5}  ... displaying 10 of 9994 total bound parameter sets ...  {'order_id': 9993, 'order_date': datetime.datetime(2022, 11, 19, 0, 0), 'ship_mode': 'Standard Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Costa Mesa', 'state': 'California', 'postal_code': 92627, 'region': 'West', 'category': 'Office Supplies', 'sub_category': 'Paper', 'product_id': 'OFF-PA-10004041', 'quantity': 4, 'discout': 0.9, 'selling_price': 29.1, 'profit': -0.8999999999999986}, {'order_id': 9994, 'order_date': datetime.datetime(2022, 7, 17, 0, 0), 'ship_mode': 'Second Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Westminster', 'state': 'California', 'postal_code': 92683, 'region': 'West', 'category': 'Office Supplies', 'sub_category': 'Appliances', 'product_id': 'OFF-AP-10002684', 'quantity': 2, 'discout': 7.2, 'selling_price': 232.8, 'profit': 22.80000000000001}]
2025-06-08 18:18:46,572 INFO sqlalchemy.engine.Engine COMMIT

9994

In [25]:
# Read All Rows: Write a SQLAlchemy query to select all rows from orders, execute it,and fetch all results.
from sqlalchemy import text

o = text('SELECT * FROM orders')

with engine.connect() as conn:
    result = conn.execute(o)
    all_rows = result.fetchall()
    for row in all_rows[:5]:
        print(row)

2025-06-08 18:18:46,751 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-06-08 18:18:46,772 INFO sqlalchemy.engine.Engine SELECT * FROM orders
2025-06-08 18:18:46,792 INFO sqlalchemy.engine.Engine [generated in 0.04134s] {}
(1, datetime.datetime(2023, 3, 1, 0, 0), 'Second Class', 'Consumer', 'United States', 'Henderson', 'Kentucky', 42420, 'South', 'Furniture', 'Bookcases', 'FUR-BO-10001798', 2, 5.2, 254.8, 14.800000000000011)
(2, datetime.datetime(2023, 8, 15, 0, 0), 'Second Class', 'Consumer', 'United States', 'Henderson', 'Kentucky', 42420, 'South', 'Furniture', 'Chairs', 'FUR-CH-10000454', 3, 21.9, 708.1, 108.10000000000002)
(3, datetime.datetime(2023, 1, 10, 0, 0), 'Second Class', 'Corporate', 'United States', 'Los Angeles', 'California', 90036, 'West', 'Office Supplies', 'Labels', 'OFF-LA-10000240', 2, 0.5, 9.5, -0.5)
(4, datetime.datetime(2022, 6, 18, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Fort Lauderdale', 'Florida', 33311, 'South', 'Furniture', 'Tables', 'FUR-TA-10000577', 5, 19.2, 940.8, 160.79999999999995)
(5, datetime.datetime(2022, 7, 13, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Fort Lauderdale', 'Florida', 33311, 'South', 'Office Supplies', 'Storage', 'OFF-ST-10000760', 2, 1.0, 19.0, -1.0)
2025-06-08 18:18:48,369 INFO sqlalchemy.engine.Engine ROLLBACK

### SQL Analysis Queries

In [26]:
# Total Revenue per Category: Sum selling_price grouped by category, ordered descending

# df.columns
Total_Rev = df.groupby('category')['selling_price'].sum().sort_values(ascending=False)

print(Total_Rev)

category
Technology         806873.5
Furniture          715340.7
Office Supplies    693644.5
Name: selling_price, dtype: float64

In [27]:
# Top 3 Profitable Cities: Identify the three cities with the highest total profit
#df.columns
highest_total_profit_cities = df.groupby('city')['profit'].sum().sort_values(ascending=False).head(3)

print(highest_total_profit_cities)

city
New York City    20925.7
Los Angeles      15088.4
San Francisco    10140.1
Name: profit, dtype: float64

In [28]:
#Profit Margin per Product: Compute (SUM(profit)/SUM(selling_price))*100 per product_id, list the top 25.
# df.columns


df_margin = df.groupby('product_id').agg({'profit':'sum','selling_price':'sum'})


df_margin['margin_percent']=df_margin['profit']/df_margin['selling_price'] * 100
# print(df_margin)

df_margin['margin_percent'].sort_values(ascending=False).head(25)

product_id
OFF-AP-10000124    31.972789
FUR-FU-10001379    31.623932
TEC-AC-10002380    29.824561
OFF-EN-10003798    26.144756
OFF-LA-10000414    24.085576
OFF-ST-10001627    23.469388
OFF-PA-10001260    20.091324
OFF-PA-10004782    20.091324
OFF-SU-10000946    19.295671
OFF-AR-10000411    19.075145
TEC-MA-10003493    18.981481
TEC-MA-10000904    18.967587
TEC-AC-10004209    18.938836
OFF-AP-10000252    18.518519
FUR-BO-10002202    18.367347
OFF-EN-10001028    17.864476
OFF-PA-10003309    17.780062
OFF-BI-10003963    17.695473
TEC-PH-10004774    17.627677
OFF-AP-10003099    17.525773
OFF-AR-10004511    17.525773
TEC-AC-10004114    17.331813
OFF-AP-10001492    17.282127
FUR-TA-10003837    17.184265
OFF-PA-10003729    17.184265
Name: margin_percent, dtype: float64

In [29]:
# Order Counts by Shipping Mode: Count order_id per ship_mode, ordered descending.
#df.head()


order_counts = df.groupby('ship_mode')['order_id'].count().sort_values(ascending=False)

print(order_counts)

ship_mode
Standard Class    5962
Second Class      1945
First Class       1538
Same Day           543
Name: order_id, dtype: int64

In [45]:
# Month with Highest Orders: Find the month number (MONTH(order_date)) with the greatest count of order_id.


month_with_highest_orders = df.groupby((df['order_date']).dt.month)['order_id'].count().sort_values(ascending=False)
print(month_with_highest_orders)

order_date
7     905
10    861
1     858
8     858
12    852
4     848
11    836
3     835
5     821
2     800
6     783
9     737
Name: order_id, dtype: int64

In [43]:
# Top 5 Most Discounted Products: Select product_id and discount, ordered by discount descending.

top_5_discounted_products = df[['product_id','discout']].sort_values('discout',ascending = False).head(5)

print(top_5_discounted_products)

           product_id  discout
2697  TEC-MA-10002412    905.6
8153  TEC-CO-10004722    560.0
4190  TEC-CO-10004722    525.0
6826  TEC-CO-10004722    525.0
9039  OFF-BI-10000545    494.5

In [44]:
# Top 3 Cities by Sales: Sum selling_price per city, list the top three
top_3_cities = df.groupby('city')['selling_price'].sum().sort_values(ascending=False).head(3)

print(top_3_cities)

city
New York City    247205.7
Los Angeles      169758.4
Seattle          115358.7
Name: selling_price, dtype: float64

In [61]:
# Average Profit for 2023: Calculate the average profit for orders where YEAR(order_date)=2023

avg_profit_2023 = df[df['order_date'].dt.year == 2023]['profit'].mean()

print(avg_profit_2023)

20.889348396207385

In [63]:
# Sub-Category Sales Ranking: Sum selling_price by sub_category, show the top five.

sub_category_ranking = df.groupby('sub_category')['selling_price'].sum().sort_values(ascending=False).head(5)

print(sub_category_ranking)

sub_category
Phones     318008.3
Chairs     316825.1
Storage    215908.0
Tables     199361.2
Binders    196038.6
Name: selling_price, dtype: float64

In [66]:
# Average Selling Price per Category: Compute average selling_price for each category, ordered descending

avg_category_ranking = df.groupby('category')['selling_price'].sum().sort_values(ascending=False)

print(avg_category_ranking)

category
Technology         806873.5
Furniture          715340.7
Office Supplies    693644.5
Name: selling_price, dtype: float64

In [67]:
#Top 10 Products by Order Count: Count order_id per product_id, list the top ten.

top_10_products = df.groupby('product_id')['order_id'].count().sort_values(ascending=False).head(10)

print(top_10_products)

product_id
OFF-PA-10001970    19
TEC-AC-10003832    18
FUR-FU-10004270    16
FUR-CH-10001146    15
TEC-AC-10003628    15
FUR-CH-10002647    15
TEC-AC-10002049    15
FUR-CH-10002880    14
FUR-CH-10003774    14
OFF-PA-10002377    14
Name: order_id, dtype: int64

In [68]:
# Top 5 Profitable Products: Sum profit per product_id, list the top five.
top_5_profitable_products = df.groupby('product_id')['profit'].sum().sort_values(ascending=False).head(5)

print(top_5_profitable_products)

product_id
TEC-CO-10004722    5644.0
TEC-MA-10002412    3624.4
OFF-BI-10003527    3435.3
TEC-CO-10001449    2631.2
FUR-CH-10002024    2246.2
Name: profit, dtype: float64

In [70]:
# Year with Highest Sales: Find YEAR(order_date) with maximum sum of selling_price.

highest_sale_year = df.groupby(df['order_date'].dt.year)['selling_price'].sum().sort_values(ascending=False).head(1)

print(highest_sale_year)

order_date
2023    1120268.5
Name: selling_price, dtype: float64

In [72]:
# Region with Lowest Discount: Identify region with the lowest average discount.

lowest_discount_region = df.groupby('region')['discout'].mean().sort_values(ascending=True).head(1)

print(lowest_discount_region)

region
Central    7.490917
Name: discout, dtype: float64

In [73]:
#  Yearly Sales Growth: Show total sales (SUM(selling_price)) per year, ordered by year.

yearly_sale_growth = df.groupby(df['order_date'].dt.year)['selling_price'].sum().sort_values(ascending=False)

print(yearly_sale_growth)

order_date
2023    1120268.5
2022    1095590.2
Name: selling_price, dtype: float64

In [84]:
# Profit Contribution by Category: For each category, compute SUM(profit)*100 / (SELECT SUM(profit) FROM orders).

total_profit = df['profit'].sum()

profit_contribution_by_category = df.groupby('category')['profit'].sum() * 100 / total_profit

print(profit_contribution_by_category)

category
Furniture          32.402945
Office Supplies    30.343079
Technology         37.253977
Name: profit, dtype: float64

In [85]:
# Most Common Shipping Mode: Find the single ship_mode used by the most orders.

most_common_ship_mode = df.groupby('ship_mode')['order_id'].count().sort_values(ascending=False).head(1)

print(most_common_ship_mode)

ship_mode
Standard Class    5962
Name: order_id, dtype: int64

In [86]:
# Highest Average Order Value by Region: Determine which region has the highest average selling_price

highest_avg_order_value = df.groupby('region')['selling_price'].mean().sort_values(ascending=False).head(1)

print(highest_avg_order_value)

region
South    233.340432
Name: selling_price, dtype: float64

In [89]:
# Category & Sub-Category Sales: Sum selling_price for each (category,sub_category) pair.

cat_sub_cat_sales = df.groupby(['category','sub_category'])['selling_price'].sum()

print(cat_sub_cat_sales )

category         sub_category
Furniture        Bookcases       110816.1
                 Chairs          316825.1
                 Furnishings      88338.3
                 Tables          199361.2
Office Supplies  Appliances      103697.7
                 Art              26259.8
                 Binders         196038.6
                 Envelopes        15917.2
                 Fasteners         2938.9
                 Labels           11994.9
                 Paper            75831.3
                 Storage         215908.0
                 Supplies         45058.1
Technology       Accessories     161604.6
                 Copiers         144358.9
                 Machines        182901.7
                 Phones          318008.3
Name: selling_price, dtype: float64

In [92]:
#  Top 3 Profitable Products per Sub-Category: For each sub_category, list the top three product_id by total profit.

top_3_profitable_products = df.groupby(['sub_category','product_id'])['profit'].sum()

print(top_3_profitable_products)

sub_category  product_id
Accessories   TEC-AC-10000023     27.9
              TEC-AC-10000057     26.9
              TEC-AC-10000109    127.3
              TEC-AC-10000158    108.3
              TEC-AC-10000171     22.2
                                 ...
Tables        FUR-TA-10004575    770.5
              FUR-TA-10004607    242.9
              FUR-TA-10004619    367.9
              FUR-TA-10004767     19.0
              FUR-TA-10004915    748.1
Name: profit, Length: 1862, dtype: float64

In [94]:
# Monthly Order Counts for 2023: Count order_id by MONTH(order_date) for YEAR(order_date)=2023, list in descending order.

monthly_orders_counts_2023 = (df[df["order_date"].dt.year == 2023].groupby(df["order_date"].dt.month)["order_id"].count().sort_values(ascending=False))


print(month_with_highest_orders)

order_date
2022    5037
2023    4957
Name: order_id, dtype: int64

In [96]:
# States with Lowest Sales: Identify the ten state values with the smallest total selling_price.

lowest_sales_states = df.groupby('state')['selling_price'].sum().sort_values(ascending=True).head(10)

print(lowest_sales_states)

state
North Dakota             877.7
West Virginia           1170.6
Maine                   1239.9
South Dakota            1276.8
Wyoming                 1536.0
District of Columbia    2789.3
Kansas                  2815.5
Idaho                   4225.2
Iowa                    4413.1
New Mexico              4619.0
Name: selling_price, dtype: float64

In [98]:
#  Top 5 States by Revenue: Find the five state values contributing most to total revenue.
highest_5_sales_states = df.groupby('state')['selling_price'].sum().sort_values(ascending=False).head(5)

print(highest_5_sales_states)

state
California      441657.0
New York        299597.5
Texas           164276.9
Washington      133779.7
Pennsylvania    112417.4
Name: selling_price, dtype: float64

In [99]:
# Average Discount by Sub-Category: Compute average discount per sub_category, ordered descending.
avg_disc_sub_category= df.groupby('sub_category')['discout'].mean().sort_values(ascending=False)

print(avg_disc_sub_category)

sub_category
Copiers        76.045588
Machines       55.289565
Tables         23.475862
Chairs         18.484441
Bookcases      17.341667
Phones         13.398988
Storage         9.115839
Supplies        9.115263
Appliances      7.944850
Accessories     7.619871
Binders         4.577413
Furnishings     3.345559
Envelopes       2.255118
Paper           2.057445
Labels          1.167857
Art             1.130905
Fasteners       0.465899
Name: discout, dtype: float64

In [100]:
# Top 10 Products by Revenue: Sum selling_price per product_id, list the top ten by total revenue.
top_10_products_by_revenue = df.groupby('product_id')['selling_price'].sum().sort_values(ascending=False).head(10)

print(top_10_products_by_revenue)

product_id
TEC-CO-10004722    59514.0
OFF-BI-10003527    26525.3
TEC-MA-10002412    21734.4
FUR-CH-10002024    21096.2
OFF-BI-10001359    19090.2
OFF-BI-10000545    18249.0
TEC-CO-10001449    18151.2
TEC-MA-10001127    17906.4
OFF-BI-10004995    17354.8
OFF-SU-10000151    16325.8
Name: selling_price, dtype: float64